#!/bin/sh

[ -z $(pwd | grep qemu) ] && cd ~/qemu/ ; [ $# -lt 3 ] && { 
    echo "Usage = qemu-install <Install Image> <Virtual Disk Image> <Memory>"
    echo "Example = qemu-install manjaro.iso manjaro.qcow2 6G"
    exit
} || qemu-system-x86_64 -enable-kvm -boot menu=off -cdrom $HOME/qemu/iso/"$1" -drive file=$HOME/qemu/vdd/"$2" -m $3 -cpu host -smp $(( $(nproc --all) / 2 )) -vga virtio -display sdl,window-close=on,gl=on -nic user,model=virtio
