#!/bin/sh

[ -z $(pwd | grep qemu) ] && cd ~/qemu/ ; [ $# -lt 2 ] && { 
    echo "Usage = qemu-run <Virtual Disk Image> <Memory>"
    echo "Example = qemu-run Manjaro.qcow2 6G"
    exit
} || qemu-system-x86_64 -enable-kvm -boot menu=off -drive file=$HOME/qemu/vdd/"$1" -m $2 -cpu host -smp $(( $(nproc --all) / 2 )) -vga virtio -display sdl,window-close=on,gl=on -nic user,model=virtio
