#!/bin/sh

[ -z $(pwd | grep qemu) ] && cd ~/qemu/ ; [ $# -lt 3 ] && { 
    echo "Usage = qemu-mkdisk <Name> <Size> <Format>"
    echo "Example = qemu-mkdisk Manjaro.qcow2 20G qcow2"
    exit
} ||  qemu-img create -f $3 $1 $2
